export const SET_SINGER = "SET_SINGER"

export const SET_PLAYING = "SET_PLAYING"

export const SET_FULLSCREEN = "SET_FULLSCREEN"

export const SET_PLAYLIST = "SET_PLAYLIST"

export const SET_SEQUENCELIST = "SET_SEQUENCELIST"

export const SET_PLAYMODE = "SET_PLAYMODE"

export const SET_CURRENTINDEX = "SET_CURRENTINDEX"

export const DELETE_PLAYLIST = "DELETE_PLAYLIST"

export const DELETE_SEQUENCELIST = "DELETE_SEQUENCELIST"

export const SET_PLAYER = "SET_PLAYER"

export const SET_RANKBAR = "SET_RANKBAR"

